# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Run tests, build, and deploy to internal track"
  lane :deploy_alpha do
    # Run Flutter tests
    Dir.chdir("../..") do
      sh "flutter test"
    end

    # Build App Bundle using Flutter to ensure versions from pubspec.yaml are injected
    sh "flutter build appbundle --release"

    # Upload to Play Store Closed Testing Track (Alpha)
    upload_to_play_store(
      track: 'alpha',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: ENV['GOOGLE_APPLICATION_CREDENTIALS'],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
